{
  "version": "0.1.0",
  "name": "forge-solana",
  "programs": {
    "localnet": {
      "forge_solana": "ForgeYourTokenProgramId11111111"
    },
    "devnet": {
      "forge_solana": "ForgeYourTokenProgramId11111111"
    },
    "mainnet": {
      "forge_solana": "ForgeYourTokenProgramId11111111"
    }
  },
  "metadata": {
    "address": "ForgeYourTokenProgramId11111111"
  }
}
