[package]
name = "forge-solana"
version = "0.1.0"

[programs.devnet]
forge_solana = "BJ81sbW7WqtvujCHJ2RbNM3NDBBbH13sEFDJ8soUzBJF"

[programs.localnet]
forge_solana = "BJ81sbW7WqtvujCHJ2RbNM3NDBBbH13sEFDJ8soUzBJF"

[programs.mainnet]
forge_solana = "11111111111111111111111111111111"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-wallet.json"

[scripts]
test = "anchor test"
