[package]
name = "forge-solana"
version = "0.1.0"

[programs.devnet]
forge_solana = "DkkU1jrPLiK2uEnJTBicEijdyyttr2rXHQWCijtRRgUz"

[programs.localnet]
forge_solana = "DkkU1jrPLiK2uEnJTBicEijdyyttr2rXHQWCijtRRgUz"

[programs.mainnet]
forge_solana = "11111111111111111111111111111111"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-wallet.json"

[scripts]
test = "anchor test"
