[package]
name = "forge_solana"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.28"
anchor-spl = "0.28"
spl-token = "4"

[profile.release]
overflow-checks = true
lto = true
codegen-units = 1
